[server]
enableStaticServing = true

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Thin-Trial.otf"
family = "Styrene B"
weight = 100

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Light-Trial.otf"
family = "Styrene B"
weight = 300

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Regular-Trial.otf"
family = "Styrene B"
weight = 400

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Medium-Trial.otf"
family = "Styrene B"
weight = 500

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Bold-Trial.otf"
family = "Styrene B"
weight = 700

[[theme.fontFaces]]
url = "app/static/Styrene_B_Family/StyreneB-Black-Trial.otf"
family = "Styrene B"
weight = 900

[theme]
base = "dark"
primaryColor = "#3A506B"
backgroundColor = "#0B132B"
secondaryBackgroundColor = "#1C2541"
textColor = "#FFFFFF"
linkColor = "#5BC0BE"
linkUnderline = false

font = "Styrene B, sans-serif"
baseFontSize = 16
baseFontWeight = 300
headingFont = "Styrene B, sans-serif"
headingFontSizes = ["2.5rem", "2rem", "1,75rem"]
headingFontWeights = [700, 500, 400]
# codeFont = "Fira Code"
# codeFontSize = "0.8rem"
baseRadius = "small"
buttonRadius = "large"
# dataframeBorderColor
# dataframeBorderColor
dataframeHeaderBackgroundColor = "#1C2541"